import { Check, ShieldCheck, Zap } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import LanguageSwitcher from './LanguageSwitcher'
import DashboardPreview from './landing/DashboardPreview'
import ThemeToggle from './ThemeToggle'

export default function AuthLayout({ title, subtitle, children }) {
  const { t } = useTranslation(); const benefits=t('auth.layout.benefits',{returnObjects:true})
  return <div className="bm-auth relative flex min-h-screen bg-slate-50 dark:bg-slate-950"><div className="absolute right-4 top-4 z-20 flex items-center gap-1"><LanguageSwitcher/><ThemeToggle/></div>
    <section className="bm-auth-visual relative hidden w-[46%] shrink-0 overflow-hidden lg:flex lg:flex-col lg:justify-between"><div className="bm-auth-grid"/><div className="bm-gh-motif pointer-events-none absolute inset-0 opacity-[0.05]" aria-hidden="true"/><div className="bm-gh-edge pointer-events-none absolute inset-y-0 right-0 w-[3px] opacity-70" aria-hidden="true"/><div className="relative z-10 p-10 xl:p-14"><div className="flex items-center gap-3"><div className="bm-logo">B</div><div><span className="block text-xl font-bold text-white">BudgetMate</span><span className="text-[10px] uppercase tracking-[0.2em] text-indigo-200">{t('auth.layout.tagline')}</span></div></div><div className="mt-20 max-w-lg"><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-xs font-semibold text-indigo-100"><Zap size={13}/> Smarter money, less friction</div><h2 className="text-4xl font-bold leading-[1.08] tracking-tight text-white xl:text-5xl">{t('auth.layout.headline')}</h2><p className="mt-5 max-w-md text-base leading-7 text-indigo-100">{t('auth.layout.description')}</p><ul className="mt-8 grid gap-3 sm:grid-cols-2">{benefits.map(text=><li key={text} className="flex items-center gap-3 rounded-xl border border-white/10 bg-white/[0.06] p-3 text-sm text-white"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-white/10"><Check size={14}/></span>{text}</li>)}</ul></div></div><div className="relative z-10 mx-10 mb-8 hidden max-w-xl xl:block"><div className="rounded-[28px] border border-white/15 bg-white/10 p-2 shadow-2xl backdrop-blur"><DashboardPreview variant="compact" glass/></div></div></section>
    <section className="flex flex-1 items-center justify-center px-4 py-14 sm:px-8"><div className="w-full max-w-md"><div className="mb-7 flex items-center gap-3 lg:hidden"><div className="bm-logo bm-logo-light">B</div><div><div className="font-bold text-slate-900 dark:text-white">BudgetMate</div><div className="text-[10px] uppercase tracking-widest text-slate-400">Smart money OS</div></div></div><div className="mb-7"><div className="mb-3 inline-flex items-center gap-2 rounded-full bg-indigo-50 px-3 py-1.5 text-xs font-semibold text-indigo-700 dark:bg-indigo-500/10 dark:text-indigo-300"><ShieldCheck size={14}/> Secure account access</div><h1 className="text-3xl font-bold tracking-tight text-slate-900 dark:text-white">{title}</h1>{subtitle&&<p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">{subtitle}</p>}</div>{children}</div></section>
  </div>
}
